<?php

namespace PrenomsApiBundle\Repository;

/**
 * FirstNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirstNameRepository extends \Doctrine\ORM\EntityRepository
{
}
