<?php

namespace PrenomsApiBundle\Repository;

/**
 * MetricsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetricsRepository extends \Doctrine\ORM\EntityRepository
{
}
