PrenomsApiBundle\Entity\Metrics:
    attributes:
        id:
            groups: ['id']
        count:
            groups: ['firstname', 'year', 'sex']
        firstname:
            groups: ['year', 'sex']
        sex:
            groups: ['year']
        year:
            groups: ['firstname', 'sex']
